doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/mapping/activity'
                prefix: 'App\CivitatisSoftware\Activity\Domain'

            Booking:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/mapping/booking'
                prefix: 'App\CivitatisSoftware\Booking\Domain'

            ActivityRelated:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/mapping/activityRelated'
                prefix: 'App\CivitatisSoftware\ActivityRelated\Domain'
